[package]
name = "hexvi"
version = "0.1.0"
authors = ["ShinyJonny <jenykcz@email.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
pancurses = "0.16"
ncurses = "5.101"
hex = "0.4"
anyhow = "1.0"
